// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBh3j7jXEckyawzmOxM_UyjBN7dmK8QCUY',
    appId: '1:648857401957:android:69b64348c1f0087a3b648c',
    messagingSenderId: '648857401957',
    projectId: 'ifeed-27988',
    storageBucket: 'ifeed-27988.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC4Yg_eOVsBg7sqLtQutKawI9amhQQtMvc',
    appId: '1:648857401957:ios:53cdd7c7f895b6e83b648c',
    messagingSenderId: '648857401957',
    projectId: 'ifeed-27988',
    storageBucket: 'ifeed-27988.firebasestorage.app',
    iosBundleId: 'com.example.flutterAppIfeed',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAhAWNE9DkK88nrZK7d8_ooydBetHeECcE',
    appId: '1:648857401957:web:1d2f8eaa879e9b1b3b648c',
    messagingSenderId: '648857401957',
    projectId: 'ifeed-27988',
    authDomain: 'ifeed-27988.firebaseapp.com',
    storageBucket: 'ifeed-27988.firebasestorage.app',
    measurementId: 'G-X0GE4FD9TF',
  );
}
